[package]
name = "zotgtfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
geo-types = "0.7.11"
gtfs-structures = "0.34.0"
polyline = "0.10.1"
reqwest = "0.11.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = {version = "1.32.0", features = ["full"] }

[[bin]]
name = "downloadstatic"
path = "src/static/download.rs"

[[bin]]
name = "processstatic"
path = "src/static/process.rs"
